#端口配置
server:
  port: 8082

#配置数据源
spring:
  datasource:
    #如果使用高版本驱动 则添加cj
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.175.128:3306/mysql_srm_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456

#Spring整合Mybatis
mybatis:
  #定义别名包
  type-aliases-package: com.example.pojo
  #导入映射文件(指定映射文件的路径)
  mapper-locations: classpath:/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #打印日志
  logging:
    level:
      com.example.mapper: debug
